---
title: "test"
author: "Vélez Jesús"
date: "5/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
setwd("~/Documents/academy/labs/biomathematics/")
library(tidyverse)
library(here)
library(xkcd)
here()
```
```{r}
sims_dir <- here("data", "sims", "social_distancing", "grid")
sims_files = list.files(sims_dir, full.names = TRUE)
```

```{r}
sims = map_dfr(sims_files, read_csv, .id = ".id") %>%
  mutate(.id = as.integer(.id),
         N_status = rowSums(select(., contains("status"))),
         βmin = case_when(
           .id %in% which(str_detect(sims_files, "βmin=0.csv")) ~ "βmin=0.0",
           .id %in% which(str_detect(sims_files, "βmin=0.1")) ~ "βmin=0.1",
           TRUE ~ "βmin=0.5"
         )) %>%
  {
    {. -> tmp} %>%
    mutate_at(vars(contains("status")), ~.x / max(tmp$N_status))
  } %>%
  pivot_longer(cols = contains("status"),
               names_to = "status",
               values_to = "fraction") %>%
  mutate(status = str_remove(status, "_status")) %>%
  filter(status %in% c("infected", "recovered", "vaccinated", "N")) %>%
  mutate(status = factor(status, levels = c("N", "infected", "recovered", "vaccinated"))) %>%
  glimpse()
```

```{r}
.top_n <- 3
top_sims <- sims %>%
  filter(step == max(step), status == "N") %>%
  group_by(βmin) %>%
  {
    {. -> tmp} %>%
    map_dfr(.x = list(Better = .top_n, Worst = -.top_n),
           .f = ~top_n(x = tmp, n = .x, wt = fraction),
           .id = "Performance")
  } %>%
  select(.id, Performance) %>%
  glimpse()
```

```{r}
highlight_sims_full <- full_join(sims, top_sims, by = c(".id", "βmin")) %>%
  mutate(Performance = factor(replace_na(Performance, "Other"), levels = c("Better", "Worst", "Other"))) %>%
  arrange(Performance) %>%
  filter(βmin != "βmin=0.1") %>%
  glimpse()
```

```{r}
theme_set(theme_bw())
theme_set(theme_xkcd())
```

```{r}
days <- seq(0, 500, 50)
steps <- 24 * days

p <- ggplot(highlight_sims_full,
       aes(
         x = step,
         y = fraction,
         group = .id,
         color = Performance
       ),
       size = 0.7) +
  geom_line() +
  facet_grid(status ~ βmin,
             scales = "free_y",
             labeller = labeller(status = set_names(c("Living", "Infected", "Recovered", "Vaccinated"), c("N", "infected", "recovered", "vaccinated")))) +
  scale_color_manual(values = c(
    alpha("#00BFC4", 1 / 2),
    alpha("#F8766D", 1 / 2),
    alpha("grey", 1 / 15)
  )) +
  scale_x_continuous(expand = c(0, NA), breaks = steps, labels = days) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Time (days)", y = "Percentage of individuals by state") +
  theme(legend.position = 'top', 
        legend.justification = 'left',
        legend.direction = 'horizontal') 

ggsave(plot = p, here("plots", "social_distancing", "ABM_proportion_curves_betas.jpg"))
#ggsave(plot = p, here("plots", "social_distancing", "ABM_proportion_curves_1.pdf"))
```

```{r}
library(kableExtra)
top_parameters <- top_sims %>%
  mutate(
    label = str_remove(basename(sims_files[top_sims$.id]), ".csv"),
    label = str_replace(label, "false|true", "0"),
    parameters = map(label, ~ str_extract_all(.x, "\\w+=\\d+(?:\\.\\d+)?")[[1]]) %>%
      map( ~ str_remove(.x, "_"))
  ) %>%
  unnest() %>%
  separate(parameters,
           into = c("parameter", "value"),
           sep = "=") %>%
  pivot_wider(
    id_cols = c(.id, Performance),
    names_from = parameter,
    values_from = value
  ) %>%
  select(-N, -nsteps) %>%
  mutate_at(vars(-Performance), as.numeric) %>%
  mutate_at(vars(
    c(
      interval_between_locks,
      start_lockdown,
      start_vaccination,
      stop_lockdown_after
    )
  ), ~ .x / 24) %>%
  mutate_at(vars(-.id, -Performance), ~ ifelse(.x > 500, Inf, .x)) %>%
  mutate(periodic_lockdown = ifelse(periodic_lockdown == 0, FALSE, TRUE)) %>%
  glimpse()

top_parameters %>%
  kable() %>%
  save_kable("performance_parameters.pdf")

webshot::install_phantomjs()
```



